-- CreateEnum
CREATE TYPE "ProjectStage" AS ENUM ('NOT_STARTED', 'PLANNING', 'PRECONSTRUCTION', 'CONSTRUCTION', 'CLOSEOUT', 'COMPLETED', 'ON_HOLD');

-- AlterTable
ALTER TABLE "Project" ADD COLUMN "stage" "ProjectStage" NOT NULL DEFAULT 'NOT_STARTED';
ALTER TABLE "Project" ADD COLUMN "progressPercent" INTEGER NOT NULL DEFAULT 0;
