#!/usr/bin/env node
/**
 * Post-build sanity for PWA artifacts (run after `npm run build` in frontend).
 * Does not replace manual install / offline checks on devices.
 */
import { existsSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const sw = join(root, "public", "sw.js");
const workerGlobNote = "public/worker-*.js (custom Workbox worker when present)";

if (!existsSync(sw)) {
  console.error("pwa-verify: missing public/sw.js — run production build first.");
  process.exit(1);
}

console.log("pwa-verify: public/sw.js present");
console.log(`pwa-verify: ${workerGlobNote} optional (generated by next-pwa)`);
console.log(
  "pwa-verify: manifest start_url is /dashboard — proxy sends unauthenticated users to /sign-in for protected routes;",
);
console.log("pwa-verify: OK");
