ALTER TYPE "ActivityType" ADD VALUE 'MAINTENANCE_SCHEDULE_CREATED';
ALTER TYPE "ActivityType" ADD VALUE 'MAINTENANCE_SCHEDULE_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE 'MAINTENANCE_SCHEDULE_COMPLETED';
ALTER TYPE "ActivityType" ADD VALUE 'MAINTENANCE_WORK_ORDERS_GENERATED';
